! This is a strongly reduced header file for those
! MPI variables used in PDAF MPI calls. This is only
! intended for compilation without a real MPI library.

      INTEGER MPI_STATUS_SIZE
      PARAMETER (MPI_STATUS_SIZE=4)

      INTEGER MPI_INTEGER, MPI_REAL, MPI_DOUBLE_PRECISION, MPI_REAL8
      PARAMETER (MPI_REAL=26,MPI_DOUBLE_PRECISION=27,MPI_INTEGER=28,MPI_REAL8=27)
 
      INTEGER MPI_LOGICAL, MPI_UNDEFINED
      PARAMETER (MPI_LOGICAL=29,MPI_UNDEFINED=30)

      INTEGER MPI_COMM_WORLD
      PARAMETER (MPI_COMM_WORLD=91)

      INTEGER MPI_COMM_NULL
      PARAMETER (MPI_COMM_NULL=92)
 
  INTEGER MPI_SUM, MPI_MAX
